# Generated by Django 5.0 on 2024-01-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_language_ott_userpreference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreference',
            old_name='languages',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='userpreference',
            old_name='ott_prefences',
            new_name='ott',
        ),
    ]
